### PR TITLE
Updated the sbatch command logic

### PR DESCRIPTION
**Pull request by jakekolessar**
Made improvements to sbatch command

### CODE REVIEW

**Review by laszewsk — COMMENTED** [review]
this is a bug

filename = [file for file in os.listdir(self.path) if file.endswith('.slurm')][0]

**Review by laszewsk — COMMENTED** [review]
this is a bug

filename = [file for file in os.listdir(self.path) if file.endswith('.slurm')][0]

this is hardcoded

was: 
def filter_dict(dictionary, string):
        filtered = {key.split('__',1)[1]: value for (key, value)
                    in dictionary.items() if string in key}
        return filtered

suggest: 

def filter_dict(dictionary, string, seperator="__"):
        filtered = {key.split(seperator,1)[1]: value for (key, value)
                    in dictionary.items() if string in key}
        return filtered

**Review by laszewsk — COMMENTED** [review]
this is a bug

filename = [file for file in os.listdir(self.path) if file.endswith('.slurm')][0]

this is hardcoded

was: 
def filter_dict(dictionary, string):
        filtered = {key.split('__',1)[1]: value for (key, value)
                    in dictionary.items() if string in key}
        return filtered

suggest: 

def filter_dict(dictionary, string, seperator="__"):
        filtered = {key.split(seperator,1)[1]: value for (key, value)
                    in dictionary.items() if string in key}
        return filtered

why is this o longer safe_load?

 with open(self.config_path, 'r') as file:
            self.json = json.load(file)

**Review by laszewsk — COMMENTED** [review]
os.mkdirs used to have a race condition and did not work properly on all systems. therefor we had Shell.mkdir is the racecondition bug fixed?

**Comment by jakekolessar** [comment]
> this is a bug
> 
> filename = [file for file in os.listdir(self.path) if file.endswith('.slurm')][0]

Fixed this by passing in script name to command

> this is hardcoded
> 
> was: def filter_dict(dictionary, string): filtered = {key.split('__',1)[1]: value for (key, value) in dictionary.items() if string in key} return filtered
> 
> suggest:
> 
> def filter_dict(dictionary, string, seperator="__"): filtered = {key.split(seperator,1)[1]: value for (key, value) in dictionary.items() if string in key} return filtered

Added separator as argument

> 
> why is this o longer safe_load?
> 
> with open(self.config_path, 'r') as file: self.json = json.load(file)

I switched to a json file, which does not have safe_load method

**Review by laszewsk — APPROVED** [review]
certain things seem not corretc, but i pull so we move on

**Pull request merged**
